### ISSUE TITLE
Missing Sharecodes

### ISSUE THREAD

**Issue by ncd76** [TotalPerformanceData/gmaxfeed#6]
https://www.tpd.zone/race-status/

No Sharecode:
15-Nov Plumpton
14- Nov - All USA races
13-Nov Cheltenham
13 - Nov - All in as estimated

No Tracker Data:
13 - Nov - All races
14 - All USA Races

**Comment by ncd76** [comment]
GMax don't track Cheltenham - set to inactive
GMax don't list French so all deactivated

**Comment by gos-qs** [comment]
Fixed
